version: '3.3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_DATABASE: 'twitchbot'
      MYSQL_USER: 'sqluser'
      MYSQL_PASSWORD: 'changeme'
  app:
    build: .
    ports:
      - '8313:8080'
    environment:
      WAIT_HOSTS: mysql:3306
      DB_USERNAME: 'sqluser'
      DB_PASSWORD: 'changeme'